# Generated by Django 3.0.5 on 2020-11-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocrudmongodbapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='id',
            new_name='post_id',
        ),
    ]
